### PR TITLE
style:首页样式优化

### PR DESCRIPTION
**Pull request by kankan-web**
## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation update
- [ ] Performance improvement
- [ ] Test related changes
- [ ] Security fix
- [ ] Dependency update
- [ ] Revert changes
- [ ] Other... Please describe:

## What is the current behavior?

- Closes #
- Related to #

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by coderz-w** [comment]
> ## PR Type
> What kind of change does this PR introduce?
> 
> * [ ]  Bugfix
> * [x]  Feature
> * [ ]  Code style update (formatting, local variables)
> * [ ]  Refactoring (no functional changes, no api changes)
> * [ ]  Build related changes
> * [ ]  CI related changes
> * [ ]  Documentation update
> * [ ]  Performance improvement
> * [ ]  Test related changes
> * [ ]  Security fix
> * [ ]  Dependency update
> * [ ]  Revert changes
> * [ ]  Other... Please describe:
> 
> ## What is the current behavior?
> * Closes #
> * Related to #
> 
> ## What is the new behavior?
> ## Does this PR introduce a breaking change?
> * [ ]  Yes
> * [x]  No
> 
> ## UI Changes
> ## Other information



> ## PR Type
> What kind of change does this PR introduce?
> 
> * [ ]  Bugfix
> * [x]  Feature
> * [ ]  Code style update (formatting, local variables)
> * [ ]  Refactoring (no functional changes, no api changes)
> * [ ]  Build related changes
> * [ ]  CI related changes
> * [ ]  Documentation update
> * [ ]  Performance improvement
> * [ ]  Test related changes
> * [ ]  Security fix
> * [ ]  Dependency update
> * [ ]  Revert changes
> * [ ]  Other... Please describe:
> 
> ## What is the current behavior?
> * Closes #
> * Related to #
> 
> ## What is the new behavior?
> ## Does this PR introduce a breaking change?
> * [ ]  Yes
> * [x]  No
> 
> ## UI Changes
> ## Other information

麻烦贴一下效果图

**Comment by kankan-web** [comment]
首页1
首页2
首页3
首页4
首页5

**Comment by kankan-web** [comment]
> > ## PR Type
> 
> 麻烦贴一下效果图

大概是上面那样

**Pull request merged**
